---
title: "AGE_65PLUS_COUNTIES"
author: "Anish Mangipudi"
format: html
editor: visual
---

```{r}


library(tidycensus)
library(tidyverse)
library(choroplethr)
library(choroplethrMaps)
library(ggplot2)
library(scales)
 
df = get_acs(geography = "County",
                       variables = c(pop_65_plus = "S0101_C01_030"),
                        survey    = "acs5",
                        year      = 2021,
                        output    = "wide",
                         cache_table = TRUE)
df$NAME = tolower(df$NAME)
names(df) <-c("region", "county.name state.name" ,"county.fips.character" ,"value", "state.abb")
df$region <- sub("0+$", "", df$region)
df$region <- as.double(df$region)

county_choropleth(df, 
                 title         = "POPULATION 65+ \n2021 5-YEAR ACS S0101_C01_030",
                 legend        = "POPULATION")

ggplot(df, aes(y = value)) +
  geom_boxplot(color="red", fill="orange", alpha=1) + 
  scale_y_continuous(label=comma) +
  ggtitle("POPULATION DISTRIBUTION STATES\n WITH POPULATION 65+") +
  xlab("")+
ylab("POPULATION")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

```

You can add options to executable code like this

```{r}
#| message: false
#| message: false

library(tidycensus)
library(tidyverse)
library(choroplethr)
library(choroplethrMaps)
library(scales)


df = get_acs(geography = "County",
             variables = c(pop_65_plus = "S0101_C01_030"),
             survey    = "acs5",
             year      = 2021,
             output    = "wide",
             cache_table = TRUE)
total_df = get_acs(geography = "County",
             variables = c(total = "S0101_C01_001"),
             survey    = "acs5",
             year      = 2021,
              output    = "wide",
              cache_table = TRUE)
percent_df  = get_acs(geography = "County",
                     variables = c(total = "S0101_C01_001"),
                     survey    = "acs5",
                     year      = 2021,
                     output    = "wide",
                     cache_table = TRUE)

names(df) <-c("region", "county.name state.name" ,"county.fips.character" ,"value", "state.abb")
names(percent_df) <-c("region", "county.name state.name" ,"county.fips.character" ,"value", "state.abb")
names(total_df) <-c("region", "county.name state.name" ,"county.fips.character" ,"value", "state.abb")



df$region = tolower(df$region)
percent_df$region = tolower(percent_df$region)
total_df$region = tolower(total_df$region)
df$region <- sub("0+$", "", df$region)
df$region <- as.double(df$region)
total_df$region <- sub("0+$", "", total_df$region)
total_df$region <- as.double(total_df$region)
percent_df$region <- sub("0+$", "", percent_df$region)
percent_df$region <- as.double(percent_df$region)
percent_df$value = ((df$value/total_df$value) * 100)
total_df$value = total_df$value - df$value
county_choropleth(percent_df,
                 title = "PERCENT POPULATION OVER 65 \n2021 5-YEAR ACS S0101_C01_001",
                 legend = "PERCENTAGE"
                 )

ggplot(percent_df, aes(y = value)) +
  geom_boxplot(color="red", fill="orange", alpha=1) + 
  scale_y_continuous(label=comma) +
  ggtitle("PERCENT DISTRIBUTION STATES\n WITH POPULATION 65+") +
  xlab("")+
ylab("POPULATION")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) 





```

The `echo: false` option disables the printing of code (only output is displayed).
